baseURL: "https://incub4t0r.github.io/"
languageCode: "en-us"
title: "foursight"
theme: "PaperMod"
publishdir: "incub4t0r.github.io"

enableInlineShortcodes: true
enableEmoji: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                # - name: Archive
                #   url: archives
                #   weight: 1
                # - name: Search
                #   url: search/
                #   weight: 2
                - name: Tags
                  url: tags/
                  weight: 4
                - name: Categories
                  url: categories/
                  weight: 3
                - name: About me
                  url: aboutme
                  weight: 5
taxonomies:
    category: categories
    tag: tags
    # series: series

params:
    # env: production # to enable google analytics, opengraph, twitter-cards and schema.
    homeInfoParams:
        Title: "hello world! 👋 "
        Content: >
            This is foursight, f0ur3y3s' website.\
            
            I post project writeups and ctf writeups from time to time.
        # imageUrl: "<imageposting link>" # optional
            
    socialIcons:
        - name: github
          url: "https://github.com/incub4t0r/"
        - name: hackthebox
          url: "https://app.hackthebox.eu/profile/269039"

    ShowShareButtons: true

    # label:
    #     text: ""
    #     icon: /static/f0ur3y3s.png
    #     iconHeight: 35
